### ISSUE TITLE
Sort by and visualize ranking status of matches 

### ISSUE THREAD

**Issue by YannCebron** [sammdot/spectra-refresh#1]
When there are multiple matches, it's not obvious which of the found candidates has "incomplete/not reliable" or "complete" match from the list of results. User has to click on each entry to see the status.

I'd propose to sort by ranking (from best to worst descending) and/or visualize status of each entry in the list so I can pick the "safe" variants first.

---
as a sample, see current results/order for `Germany` where "good" and "bad" results seem to be in random order

| Chords | Ranking |
|---|---|
| SKWRERL/TPHEU | Incomplete match. Not reliable. |
| SKWRERPL/TPH*EU | Found complete match. |
| SKWRERPL/TPHAEU | Incomplete match. Not reliable. |
| SKWRERPL/TPHEU | Found complete match. |
| SKWRERPL/TPHREU | Incomplete match. Not reliable. |

**Comment by sammdot** [comment]
I'm not sure that I can do this with just the data I get from Spectra -- all I get is a list of outlines seemingly in no particular order, and I'd have to query each outline individually.

![List of outlines for 'test'](https://user-images.githubusercontent.com/7952620/178121890-addb65de-3c1a-4ff4-9ed9-65779520b9c6.png)

**Comment by YannCebron** [comment]
I see. is it not possible then to perform the request for each found outline to obtain its status and add this information in a second pass?
